"""Versioned shared motion semantics; boss identity is separate metadata."""

STATES = ("NON_THREAT", "IDLE", "WALK", "RUN", "TURN", "ATTACK_WINDUP",
          "ACTIVE_ATTACK", "RECOVERY", "COMBO_CONTINUATION", "FEINT")
ATTACK_TYPES = ("HORIZONTAL_SLASH", "VERTICAL_SLASH", "DIAGONAL_SLASH", "THRUST", "SWEEP",
                "GRAB", "JUMP_ATTACK", "OVERHEAD_ATTACK", "SPIN_ATTACK", "PROJECTILE", "CHARGE",
                "AOE", "MULTI_HIT_COMBO", "UNKNOWN_ATTACK")
MOVEMENTS = ("IDLE", "WALK", "RUN", "TURN", "FEINT", "UNKNOWN_MOVEMENT")
PHASES = ("ATTACK_WINDUP", "ACTIVE_ATTACK", "RECOVERY", "COMBO_CONTINUATION", "UNKNOWN_PHASE")
IMPACT_EVIDENCE = ("OBSERVED_CONTACT", "ESTIMATED_COUNTERFACTUAL", "NO_CONTACT", "OCCLUDED", "OUT_OF_CLIP")
DIRECTIONS = ("LEFT", "RIGHT", "FORWARD", "BACK", "NEUTRAL", "UNKNOWN")
NEGATIVE_REASONS = ("IDLE", "WALKING", "RUNNING", "TURNING", "HEALING", "PLAYER_ATTACK",
                    "BOSS_BLOCK", "BOSS_DEFLECT", "RECOVERY", "CAMERA_ROTATION", "CAMERA_SHAKE",
                    "PARTICLES", "PROSTHETIC_EFFECT", "DEATHBLOW", "CUTSCENE", "NONATTACK_JUMP",
                    "FEINT", "HUD_FLASH", "OCCLUSION", "OTHER_REVIEWED_NON_THREAT")
